### ISSUE TITLE
Check for repeated strings that can be turned into a constant in JS files

### ISSUE THREAD

**Issue by drewbrokke** [natecavanaugh/check-source-formatting#10]
Include some regex along the lines of `('[a-zA-Z#-]+')([\s\S]+\1){1,}` to see if a string is used multiple times in the same JS file and therefore would be a candidate for a constant like `var STR_REPEATED = 'repeated';`

**Comment by mthadley** [comment]
Given that a lot of source formatting happen's in relation to this, I think it might be a good idea. 

Though one thing I've been wondering for awhile now is the particular reason we do this. Is it for performance (referencing a constant instead of creating a new string), or maybe for catching typos? (Getting a `ReferenceError` instead of silently passing along the typoed string).

Thanks!

**Comment by drewbrokke** [comment]
I think it's probably both.  It's also for maintainability, so that one only has to change a single string if it needs to change for any reason. Otherwise, it would be easy to miss a usage here or there.

**Comment by mthadley** [comment]
True, though I've seen instances where `STR_REPEATED`'s value might get changed to `repeating`, at which point the variable name gets changed to `STR_REPEATING`.

**Comment by natecavanaugh** [comment]
First, I'm going to add @jbalsas, @brunobasto and @jonmak08 to this conversation, as I'm curious on their opinion of it.

To answer Mike's question, it was originally for performance, as older IE's were particularly bad at string handling, mainly around concatenation. IE 6 & 7 would exponentially create copies of the strings in memory when concatenating them, causing the GC to thrash, so this was a bit of a performance prevention measure.
It also was a way to prevent having to repeat either dynamically built objects/strings, or just long and annoying strings that aren't a lot of fun to have to type repeatedly.

However, I've been strongly reconsidering this in general, since I've always felt like it's quite the maintenance pain for a lot of cases.
My logic would be that maintenance is not just about re-writing code, but mainly about *reading* it and being able to find your way around it.
When we do something like `instance.get(STR_DISPLAY_STYLE)` and I want to find the ATTRS definition of it, I immediately need to first find what value is assigned to `STR_DISPLAY_STYLE`, then highlight that value and try to find `displayStyle`, or `displayStyleCssClass` (the other issue is that variation has creeped in).
But overall, I find it adds a level of indirection that get's annoying when trying to figure the code out.
It also adds quite a lot of noise to the top of the file before you can even get to the meat of it.

So, I've been thinking about updating the pattern in portal and plugins to selectively reverse it.

The policy I'm thinking about changing everything to is still use constants for reused objects (maps, regex objects, etc), and for one-time calculated strings (like where we're dynamically generating the classname).

But for the actual re-used strings, I would just go back to using them inline, and leaving it at that.

Curious what you guys think :)

**Comment by jbalsas** [comment]
Hey @natecavanaugh, I'd be happy if we start removing the string constants. I agree it hurts legibility more than it helps.

As you mention, we should have a clear list of scenarios where we want to avoid it for performance reasons and stop doing it for the rest.

**Comment by mthadley** [comment]
@natecavanaugh I completely agree, especially since I've always struggled with seeing the value in it. Though it does make the rules somewhat more unclear for when something should be moved to a constant.

**Comment by jonmak08** [comment]
Like what @natecavanaugh said, we used to cache JS values for performance benefits in older browser, but given that we no longer "support" these older browsers, I think it makes a lot of sense to removing these JS constants.

I think that caching objects, maps or regex at the top would be ideal since those are the only things that really get reused often;  we could say we should cache any configuration-esque values, but not strings or CSS classes.

**Comment by natecavanaugh** [comment]
@mthadley For me it's fairly clear: a constant would be any variable where you don't want the value to change, but for strings, I'd expand it to anything that's either a lot of text or something that would be more prone to falling out of sync across a file.
IMO, [these are good examples](https://github.com/liferay/liferay-plugins-ee/blob/13884f4983e50edc03f97a5e76b87d596462813c/portlets/loop-portlet/docroot/js/loop.js#L31-L63) of things that are good candidates for being constants.
Of course, for some of the strings in there, you could make an argument that certain strings (like perhaps the URLs and/or CSS classes) make sense to store as constants, as you would want those to stay consistent, but I think in those cases it should be up to the individual project to decide at what point it makes sense.

I think the main thing would be just removing the *requirement* to have all duplicated strings extracted as constants.

LMK if you have some examples that are particularly ambiguous to you :)

**Comment by mthadley** [comment]
@natecavanaugh Things like CSS classes were the main thing I was thinking about (or other mostly string-like values). But I think your rationale is solid and is something we could go off of.

**Comment by natecavanaugh** [comment]
I also just had another thought that might also help a bit with legibility for those cases where we need the constants defined:

In the Java code, we always define constants at the bottom of the file.
I was thinking, we could do the same thing with our constants *provided they're only used in functions or later in the file*.

The upsides to this approach would be:
1. not needing to scroll past a ton of them to get to the meat of the file
2. since the vars are hoisted, and being looked up at runtime, it won't throw any errors
3. The source formatter already allows for this, while still warning if it's used before it's defined inside of the same scope
4. It might make more sense to the backend guys (though that's not a huge thing it it's favor).

The cons I can see are:
1. There will always be a few exceptions where we need a var defined for use as a property on the object (mainly, our biggest scenario for this is when we define a `NAME` constant, that's also used as part of the CSS class names). I can see this situation being fairly limited.
2. Might confuse some people

What do you guys think?

**Comment by jbalsas** [comment]
Hey Nate,

I personally don't think that pushing cons to the bottom will make a big difference, I'd rather keep them on top. If we remove the requirement of duplicated strings as constants, the constant block should become smaller enough so it doesn't hurt that much.

In any case, I wouldn't super strongly object if you all guys prefer it there :wink:

**Comment by natecavanaugh** [comment]
Hey guys,
Since this one doesn't require any work done in this repo (and it's a 1.5 years old), I'm going to close this one out.

Feel free to comment though if there's still something left to discuss :)
