### ISSUE TITLE
Unknown property 'class' found, use 'className' instead

### ISSUE THREAD

**Issue by bryceosterhaus** [natecavanaugh/check-source-formatting#15]
When using metal-jsx we get errors when declaring class for elements. Wonder if it might be possible to add metal.js support and let the use choose between react/metal.

**Comment by natecavanaugh** [comment]
Heya Bryce,
Yeah, sorry about that... I believe I fixed it in one of your recent pulls (I just disabled the rule in your configuration, but for now, only for metal components, since the rule is still useful for any React rules you have).

Is it still showing up for you guys?

**Comment by bryceosterhaus** [comment]
Oh perfect. I didn't notice that previously. Thanks!

**Comment by bryceosterhaus** [comment]
Actually I just tested again and I seem to be getting the warning again.

**Comment by natecavanaugh** [comment]
@bryceosterhaus could you point me to a file where this is triggering for you? I'll take a look at it and see if I'm missing something.

Also, make sure you're running the formatter from the loop directory where the package.json is at. This is one of the current limitations that I'm hoping to resolve before the final is released, which is that the module looks for configuration from the current directory and parents, but doesn't check the parents of each file's path.
In order to do that, I'll have to do some caching to make sure I don't keep re-analyzing multiple paths over and over again.

**Comment by bryceosterhaus** [comment]
Try running it on the `components-metal/Tabs.js` in loop

**Comment by natecavanaugh** [comment]
Heya Bryce,
I've published a new release, which will fix this issue :)
Just do an `npm install -f check-source-formatting@next` to get it.

Sorry for the trouble and thanks for letting me know!

**Comment by mthadley** [comment]
Fixed it for me, thanks @natecavanaugh!
